name: Build Package

on:
  push:
    branches:
      - main

jobs:
  build-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cuda: "11.8.0"
            python: "3.11"
            torch_install_cmd: pip install torch==2.1.2+cu118 --index-url https://download.pytorch.org/whl/cu118
            sleep: 0
          - cuda: "11.8.0"
            python: "3.10"
            torch_install_cmd: pip install torch==2.1.2+cu118 --index-url https://download.pytorch.org/whl/cu118
            sleep: 20
          - cuda: "12.1.1"
            python: "3.11"
            torch_install_cmd: pip install torch==2.1.2+cu121 --index-url https://download.pytorch.org/whl/cu121
            sleep: 40
          - cuda: "12.1.1"
            python: "3.10"
            torch_install_cmd: pip install torch==2.1.2+cu121 --index-url https://download.pytorch.org/whl/cu121
            sleep: 60
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: Jimver/cuda-toolkit@v0.2.14
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda }}
          linux-local-args: '["--toolkit"]'
          use-github-cache: false
          method: "network"

      - run: sudo apt-get install ninja-build

      - name: Install PyTorch
        run: |
          pip install wheel numpy && \
          ${{ matrix.torch_install_cmd }}

      - name: Build
        run: |
          export TORCH_CUDA_ARCH_LIST="7.0;7.5;8.0;8.6;8.9;9.0+PTX"
          python setup.py bdist_wheel

      - name: Commit push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f ./dist/*.whl
          sleep ${{ matrix.sleep }}
          git commit -m 'update wheel'
          git pull --no-edit
          git push
