name: Build Package

on:
  push:
    branches:
      - main

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: Jimver/cuda-toolkit@v0.2.14
        id: cuda-toolkit
        with:
          cuda: "11.8.0"
          linux-local-args: '["--toolkit"]'

      - run: sudo apt-get install ninja-build

      - name: Install PyTorch
        run: |
          pip install wheel numpy && \
          pip install torch==2.1.2+cu118 --index-url https://download.pytorch.org/whl/cu118

      - name: Build
        run: |
          export TORCH_CUDA_ARCH_LIST="3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0+PTX"
          export BUILD_VERSION="cu$(nvcc -V | grep release | awk '{print $5}' | sed -e 's/,//' -e 's/\.//')"
          python setup.py bdist_wheel

      - name: Commit push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f ./dist/*.whl
          git commit -m 'update wheel'
          git push
